site_name: Mon Projet Flask
theme:
  name: material
  palette:
    primary: indigo
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Accueil: index.md
  - API: api.md
  - Architecture: architecture.md
  - Contribution: contributing.md
